export const SEED_EQUIPAMENTOS = [
  {
    id: "RH01",
    tipo: "Horizontal",
    modelo: "RetroLux Pro",
    modelo1: "RLX-100",
    geometria: 30,
    numeroSerie: "H-001",
    fabricante: "Medlux",
    dataAquisicao: "2023-02-15",
    calibrado: true,
    dataCalibracao: "2024-06-10",
    numeroCertificado: "CERT-2024-001",
    responsavelLocal: "Laboratório Central",
    dataEntrega: "2024-06-15",
    observacoes: "Equipamento principal de pista.",
    statusOperacional: "ATIVO"
  },
  {
    id: "RH02",
    tipo: "Horizontal",
    modelo: "RoadBeam X",
    modelo1: "",
    geometria: 30,
    numeroSerie: "H-002",
    fabricante: "RoadTech",
    dataAquisicao: "2022-11-20",
    calibrado: true,
    dataCalibracao: "2023-12-01",
    numeroCertificado: "CERT-2023-045",
    responsavelLocal: "Equipe Sul",
    dataEntrega: "2023-12-12",
    observacoes: "Em uso em campo.",
    statusOperacional: "EM_CAUTELA"
  },
  {
    id: "RV02",
    tipo: "Vertical",
    modelo: "SignReflect",
    modelo1: "SR-2",
    geometria: 0.5,
    numeroSerie: "V-120",
    fabricante: "Reflecta",
    dataAquisicao: "2021-05-05",
    calibrado: false,
    dataCalibracao: null,
    numeroCertificado: "",
    responsavelLocal: "Armazém Norte",
    dataEntrega: null,
    observacoes: "Aguardando calibração.",
    statusOperacional: "EM_CALIBRACAO"
  },
  {
    id: "RT01",
    tipo: "Tachas",
    modelo: "TachoScan",
    modelo1: "TS-10",
    geometria: 1.5,
    numeroSerie: "T-501",
    fabricante: "LuxWay",
    dataAquisicao: "2020-08-18",
    calibrado: true,
    dataCalibracao: "2022-07-20",
    numeroCertificado: "CERT-2022-010",
    responsavelLocal: "Equipe Norte",
    dataEntrega: "2022-07-30",
    observacoes: "Necessita revisão geral.",
    statusOperacional: "MANUTENCAO"
  },
  {
    id: "RH08",
    tipo: "Horizontal",
    modelo: "RoadBeam X",
    modelo1: "RBX-2",
    geometria: 30,
    numeroSerie: "H-008",
    fabricante: "RoadTech",
    dataAquisicao: "2024-01-10",
    calibrado: true,
    dataCalibracao: "2024-02-05",
    numeroCertificado: "CERT-2024-118",
    responsavelLocal: "Laboratório Central",
    dataEntrega: "2024-02-20",
    observacoes: "Backup do RH01.",
    statusOperacional: "ATIVO"
  }
];
